import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // Manual sidebar for the textbook
  textbookSidebar: [
    {
      type: 'category',
      label: 'Introduction',
      items: ['intro'],
      collapsed: false,
    },
    {
      type: 'category',
      label: 'Module 1: ROS 2 Robotic Nervous System',
      items: [
        {
          type: 'autogenerated',
          dirName: 'module-1',
        }
      ],
      collapsed: false,
    },
    {
      type: 'category',
      label: 'Module 2: Digital Twin (Gazebo & Unity)',
      items: [
        {
          type: 'category',
          label: 'Chapter 1: Physics-Based Simulation with Gazebo',
          items: [
            'module-2/chapter-1-gazebo-physics/1.1-digital-twin-intro',
            'module-2/chapter-1-gazebo-physics/1.2-gazebo-architecture',
            'module-2/chapter-1-gazebo-physics/1.3-gravity-dynamics',
            'module-2/chapter-1-gazebo-physics/1.4-collision-contact',
            'module-2/chapter-1-gazebo-physics/1.5-realtime-vs-accelerated',
            'module-2/chapter-1-gazebo-physics/1.6-gazebo-optimization'
          ],
        },
        {
          type: 'category',
          label: 'Chapter 2: Environment & World Building in Gazebo',
          items: [
            'module-2/chapter-2-world-building/2.1-world-files',
            'module-2/chapter-2-world-building/2.2-terrain-materials',
            'module-2/chapter-2-world-building/2.3-static-dynamic',
            'module-2/chapter-2-world-building/2.4-importing-meshes',
            'module-2/chapter-2-world-building/2.5-spawn-ros2',
            'module-2/chapter-2-world-building/2.6-multi-robot'
          ],
        },
        {
          type: 'category',
          label: 'Chapter 3: Sensor Simulation (LiDAR, Depth, IMU)',
          items: [
            'module-2/chapter-3-sensor-simulation/3.1-sensor-principles',
            'module-2/chapter-3-sensor-simulation/3.2-lidar-simulation',
            'module-2/chapter-3-sensor-simulation/3.3-depth-camera',
            'module-2/chapter-3-sensor-simulation/3.4-rgb-camera',
            'module-2/chapter-3-sensor-simulation/3.5-imu-simulation',
            'module-2/chapter-3-sensor-simulation/3.6-sensor-noise',
            'module-2/chapter-3-sensor-simulation/3.7-ros2-sensor-stream'
          ],
        },
        {
          type: 'category',
          label: 'Chapter 4: High-Fidelity Visualization & Interaction with Unity',
          items: [
            'module-2/chapter-4-unity-visualization/4.1-unity-role',
            'module-2/chapter-4-unity-visualization/4.2-unity-fundamentals',
            'module-2/chapter-4-unity-visualization/4.3-importing-assets',
            'module-2/chapter-4-unity-visualization/4.4-hri-simulation',
            'module-2/chapter-4-unity-visualization/4.5-physics-sync',
            'module-2/chapter-4-unity-visualization/4.6-synthetic-data'
          ],
        },
        {
          type: 'category',
          label: 'Labs',
          items: [
            'module-2/labs/lab-1-gazebo-physics',
            'module-2/labs/lab-2-world-building',
            'module-2/labs/lab-3-sensor-simulation',
            'module-2/labs/lab-4-unity-visualization',
            'module-2/labs/lab-5-digital-twin-integration'
          ],
        },
        {
          type: 'category',
          label: 'Mini Projects',
          items: [
            'module-2/mini-projects/mini-project-full-digital-twin'
          ],
        },
        {
          type: 'category',
          label: 'Tutorials',
          items: [
            'module-2/tutorials/gazebo-setup',
            'module-2/tutorials/unity-setup',
            'module-2/tutorials/ros2-integration'
          ],
        },
        {
          type: 'category',
          label: 'References',
          items: [
            'module-2/references/simulation-bibliography',
            'module-2/references/sensor-modeling-literature'
          ],
        }
      ],
      collapsed: false,
    },
    {
      type: 'category',
      label: 'Module 3: The AI-Robot Brain (NVIDIA Isaac™)',
      items: [
        {
          type: 'category',
          label: 'Chapter 1: NVIDIA Isaac Sim for Photorealistic Simulation',
          items: [
            'module-3/chapter-1-isaac-sim/1.1-ai-robot-brain-intro',
            'module-3/chapter-1-isaac-sim/1.2-omniverse-architecture',
            'module-3/chapter-1-isaac-sim/1.3-photorealistic-rendering',
            'module-3/chapter-1-isaac-sim/1.4-synthetic-data',
            'module-3/chapter-1-isaac-sim/1.5-domain-randomization',
            'module-3/chapter-1-isaac-sim/1.6-urdf-import'
          ],
        },
        {
          type: 'category',
          label: 'Chapter 2: Hardware-Accelerated Perception with Isaac ROS',
          items: [
            'module-3/chapter-2-isaac-ros/2.1-isaac-ros-overview',
            'module-3/chapter-2-isaac-ros/2.2-jetson-architecture',
            'module-3/chapter-2-isaac-ros/2.3-image-pipeline',
            'module-3/chapter-2-isaac-ros/2.4-depth-processing',
            'module-3/chapter-2-isaac-ros/2.5-vslam',
            'module-3/chapter-2-isaac-ros/2.6-localization-mapping',
            'module-3/chapter-2-isaac-ros/2.7-performance-benchmarking'
          ],
        },
        {
          type: 'category',
          label: 'Chapter 3: Autonomous Navigation with Nav2',
          items: [
            'module-3/chapter-3-nav2/3.1-nav-introduction',
            'module-3/chapter-3-nav2/3.2-nav2-architecture',
            'module-3/chapter-3-nav2/3.3-global-local-planning',
            'module-3/chapter-3-nav2/3.4-costmaps',
            'module-3/chapter-3-nav2/3.5-bipedal-constraints',
            'module-3/chapter-3-nav2/3.6-sensor-fusion-nav',
            'module-3/chapter-3-nav2/3.7-recovery-behaviors'
          ],
        },
        {
          type: 'category',
          label: 'Chapter 4: Sim-to-Real Transfer with NVIDIA Isaac',
          items: [
            'module-3/chapter-4-sim-to-real/4.1-sim-to-real-principles',
            'module-3/chapter-4-sim-to-real/4.2-perception-transfer',
            'module-3/chapter-4-sim-to-real/4.3-navigation-transfer',
            'module-3/chapter-4-sim-to-real/4.4-calibration',
            'module-3/chapter-4-sim-to-real/4.5-latency-safety',
            'module-3/chapter-4-sim-to-real/4.6-field-testing'
          ],
        }
      ],
      collapsed: false,
    },
    {
      type: 'category',
      label: 'Module 4: Advanced ROS 2 Integration & Deployment',
      items: [
        'module-4/overview',
        {
          type: 'category',
          label: 'Chapter 1: Advanced ROS 2 Integration',
          items: [
            'module-4/chapter-1-ros2-integration/1.1-ros2-integration-overview'
          ],
        },
        {
          type: 'category',
          label: 'Chapter 2: Jetson Optimization',
          items: [
            'module-4/chapter-2-jetson-optimization/2.1-jetson-optimization-basics'
          ],
        },
        {
          type: 'category',
          label: 'Chapter 3: Humanoid Locomotion',
          items: [
            'module-4/chapter-3-humanoid-locomotion/3.1-locomotion-control-basics'
          ],
        },
        {
          type: 'category',
          label: 'Chapter 4: Field Deployment',
          items: [
            'module-4/chapter-4-field-deployment/4.1-field-deployment-strategies'
          ],
        },
        {
          type: 'category',
          label: 'Labs',
          items: [
            'module-4/module-4-labs/lab-1-advanced-deployment'
          ],
        },
        {
          type: 'category',
          label: 'Assessments',
          items: [
            'module-4/module-4-assessments/module-4-assessment'
          ],
        }
      ],
      collapsed: false,
    }
  ],
};

export default sidebars;
